// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDNTHze5igaaeRAHJ8EHv5wX7k95zvR7g',
    appId: '1:409878736117:web:428f8c4702db0102c6e9bc',
    messagingSenderId: '409878736117',
    projectId: 'comma-188ee',
    authDomain: 'comma-188ee.firebaseapp.com',
    storageBucket: 'comma-188ee.appspot.com',
    measurementId: 'G-41Y9E078LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdxE8kQda5DBlqHB51AqZkJeynCSeti9I',
    appId: '1:409878736117:android:d0d9d1de311af53cc6e9bc',
    messagingSenderId: '409878736117',
    projectId: 'comma-188ee',
    storageBucket: 'comma-188ee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrJ_kEseh9RxXo4vuZfZzWJo3FnSEs6d8',
    appId: '1:409878736117:ios:a74ad8e05797a704c6e9bc',
    messagingSenderId: '409878736117',
    projectId: 'comma-188ee',
    storageBucket: 'comma-188ee.appspot.com',
    iosBundleId: 'com.example.flutterPlugin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrJ_kEseh9RxXo4vuZfZzWJo3FnSEs6d8',
    appId: '1:409878736117:ios:a74ad8e05797a704c6e9bc',
    messagingSenderId: '409878736117',
    projectId: 'comma-188ee',
    storageBucket: 'comma-188ee.appspot.com',
    iosBundleId: 'com.example.flutterPlugin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDNTHze5igaaeRAHJ8EHv5wX7k95zvR7g',
    appId: '1:409878736117:web:8c8f2cef83629524c6e9bc',
    messagingSenderId: '409878736117',
    projectId: 'comma-188ee',
    authDomain: 'comma-188ee.firebaseapp.com',
    storageBucket: 'comma-188ee.appspot.com',
    measurementId: 'G-SWMMDQ23SY',
  );
}
